# Generated by Django 5.1.1 on 2024-09-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Disaster', '0003_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
