# Generated by Django 5.1.1 on 2024-09-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disaster', '0004_remove_message_chat_room_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
        migrations.RemoveField(
            model_name='report',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='report',
            name='contact',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
